### ISSUE TITLE
Posts are not shown.

### ISSUE THREAD

**Issue by MinecraftXwinP** [antonpolishko/hugo-stellar-theme#2]
Posts are not shown. Is it still WIP?

**Comment by antonpolishko** [comment]
It's just a  one-pager template and not suitable for blogs atm. Original template https://html5up.net/stellar and most of the other ports of html5up templates are like that.

**Comment by MinecraftXwinP** [comment]
I see. Thanks for reply. Showing blog posts is in the roadmap of this theme, right?

**Comment by antonpolishko** [comment]
I'm trying to make https://github.com/gcushen/hugo-academic theme/framework and stellar to work together for my personal page. Eventually the results of that would propagate here
