### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by sveeke** [antonpolishko/hugo-stellar-theme#5]
Hi. I am quite new to Hugo but love it and your theme already. It's the first theme I tried, and so far it works like a charm. But I have two questions about stuff I can't seem to find out. Apologies up front if this isn't the right place to ask these questions.

## First question
I use `hugo new pagename.md` to create a new page in `content/`, but the page doesn't want to be created. I found out that this may be due to the absence of something named `single.html` in `themes/stellar/layouts/`, but that is as far as I have come. Also I found that your `generic.html` and `elements.html` files in `/themes/stellar/exampleSite/static/` are sort-off being used for my purpose of single pages, but having to create full html pages defeats the purpose of a static site generator like Hugo for me. That's why I try to do it with `hugo new pagename.md`. Any idea what I am doing wrong?

## Second question
Most of the css and js isn't used, which I don't like from a performance/efficiency standpoint. I plan on minimizing font-awesome to the icons I may use, removing most of unused css and js etc. But since I am not really experienced with web stuff (normally I'm not going above unix operating system stuff) I was wondering if you have any tips for me. I found a nifty css coverage tool in Chromium for example, but there are probably a lot more of these handy tools to really minimize used and transfered code :).

Thanks in advance, en also thanks for the awesome theme. I came across a typo by the way and did a pull request to fix that, but it's really minor.

**Comment by antonpolishko** [comment]
Hey,

Q.1. It's a simple port of a one page [Stellar](https://html5up.net/stellar) theme and only basic functionality of hugo is applied here. I would suggest looking into something like [Academic](https://themes.gohugo.io/academic/) to see how to implement more generic theme. Using this port as a starting point would be quite a tedious job 

Q.2. Modern approach to web is to cut size only when it's needed later :). Font Awesome is optimized more or less and is getting cashed on the client. I would use DevTools to see if something takes too much transfer space in the result and then adjust accordingly. 

Hope this helps
